### ISSUE TITLE
OBO purl points to outdated file

### ISSUE THREAD

**Issue by matentzn** [Phenomics/zebrafish-phenotype-ontology-build#3]
The purl http://purl.obolibrary.org/obo/upheno/zp.owl redirects to a file located here: 

```
http://compbio.charite.de/jenkins/job/zp-owl/lastSuccessfulBuild/artifact/zp.owl
```

which seems to be a version of ZP that is, as per ontology metadata version, not the latest:

``` 
http://purl.obolibrary.org/obo/upheno/releases/2015-11-30/zp.owl
```

Can we refresh the purl so that it points to this repo?

**Comment by matentzn** [comment]
(As a side: is there a reason why upheno is part of the purl? Should ZP not be treated the same way as any other phenotype ontology and get a proper OBO foundry release?)

**Comment by iamkoehler** [comment]
Hmmm... what is your use-case here? How important is a more recent version? (The newer one is only a few weeks younger).

**Comment by iamkoehler** [comment]
We started working on a more recent version, but since I have no funding for this, we kind of stopped at some point

**Comment by matentzn** [comment]
Ah okay.. According to the version IRI (http://purl.obolibrary.org/obo/upheno/releases/2017-07-05/zp.owl) it seemed that it was more than 1,5 years older. I am currently prepping for the workshop in the summer, and therefore I would like to work with the lastest versions when running analyses and so on.. It is not of critical importance; I can just use the version on this repo, no need to change the purl if there is no need. It is just that UPHENO is importing the older version, and so I thought I'd mention it.

Maybe we should talk a bit how ZP will be maintained in the future. I mean in the end David OS (@dosumis) and I are working on a Monarch grant targeted at improving those patterns. Not sure how well what fits. But good to know ZP is actually sleeping now.

**Comment by iamkoehler** [comment]
> Maybe we should talk a bit how ZP will be maintained in the future. I mean in the end David OS (@dosumis) and I are working on a Monarch grant targeted at improving those patterns. Not sure how well what fits. But good to know ZP is actually sleeping now.

Yes, maybe we can coordinate. I think when monarch decided to put out funding for this, we stopped work on it, but I think it should be pretty easy to do this with a few resources. Most of it is just some QC. Code is already on github etc. Shall we skype or email? I also had some previous discussion and ideas with @balhoff on ZP

**Comment by matentzn** [comment]
Superceded by move to new PURLs and ODK based repo
