### ISSUE TITLE
Get rid of abnormal(ly) and replace by dynamic

### ISSUE THREAD

**Issue by matentzn** [Phenomics/zebrafish-phenotype-ontology-build#6]
Abnormal or Abnormally.

**Comment by iamkoehler** [comment]
what do you mean by "replace by dynamic"?

**Comment by matentzn** [comment]
Just note to self; Rather than saying abnormal(ly) trying to find a way to place the correct abnormal OR abnormally (i.e. dynamically determining the correct label).

**Comment by iamkoehler** [comment]
Ok. Would be cool to add this to PATO, i.e. store that "shape" is a noun and "elongated" is an adjective, so that others could use this information as well.

**Comment by matentzn** [comment]
Superceded by replacement of label style to ZFIN default
