### ISSUE TITLE
Duplicate label and other annotations (i.e. source_information)

### ISSUE THREAD

**Issue by matentzn** [Phenomics/zebrafish-phenotype-ontology-build#7]
In particular when the spelling on one of the ZFIN label have changed, multiple rdfs:label annotations are created. Example:

ZP_0008089 : 
```
label 1: abnormal(ly) has fewer parts of type sympathetic nervous system towards norepinephrin secreting cell
label 2: abnormal(ly) has fewer parts of type sympathetic nervous system towards norepinephrine secreting cell
```

Note spelling of *norepinephrine*.

**Comment by iamkoehler** [comment]
We need a better strategy. Do you think reasoners will work? But we need to handle alt_ids etc.

**Comment by matentzn** [comment]
Superceded by move to new system
